version: 2

jobs:
  build:
    working_directory: ~/
    
    docker:
      - image: docker

    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      - run:
          name: Build image
          command: docker build -t quartic/uber-builder:${CIRCLE_BUILD_NUM} .

      - run:
          name: Run tests
          # See https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
          command: |
            docker create -e "GCLOUD_SERVICE_KEY=${GCLOUD_SERVICE_KEY}" -e "GCLOUD_PROJECT_ID=${GCLOUD_PROJECT_ID}" \
              --name test quartic/uber-builder:${CIRCLE_BUILD_NUM} /test/run_tests.sh
            docker cp $(pwd)/test test:/test
            docker start -a test

      - deploy:
          command: |
            docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
            docker push quartic/uber-builder:${CIRCLE_BUILD_NUM}
