version: 2

jobs:
  build:
    working_directory: ~/
    
    docker:
      - image: docker

    steps:
      - checkout

      - setup_remote_docker

      - run: |
          docker build -t quartic/uber-builder:${CIRCLE_BUILD_NUM} .

      - deploy:
          command: |
            docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
            docker push quartic/uber-builder:${CIRCLE_BUILD_NUM}
