version: 2

jobs:
  build:
    working_directory: ~/
    
    docker:
      - image: docker

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build image
          command: docker build -t quartic/uber-builder:${CIRCLE_BUILD_NUM} .

      - run: |
          name: Run tests
          command: |
            git clone https://github.com/sstephenson/bats.git
            pushd bats
            ./install.sh /usr/local
            popd
            bats tests.bats

      # - deploy:
      #     command: |
      #       docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
      #       docker push quartic/uber-builder:${CIRCLE_BUILD_NUM}
