version: 2

jobs:
  build:
    docker:
      - image: docker:17.07.0-ce-git

    working_directory: ~/uber-builder

    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      - run: docker build -f Dockerfile.uber   -t uber-builder   .
      - run: docker build -f Dockerfile.noober -t noober-builder .

      - run:
          name: Run tests
          command: |
            ./test/run_tests.sh uber-builder   tests.noober.bats tests.uber.bats
            ./test/run_tests.sh noober-builder tests.noober.bats

      - run: docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}

      - run:
          name: Publish Docker images
          command: |
            docker tag uber-builder quartic/uber-builder:${CIRCLE_BUILD_NUM}
            docker push quartic/uber-builder:${CIRCLE_BUILD_NUM}

            docker tag noober-builder quartic/noober-builder:${CIRCLE_BUILD_NUM}
            docker push quartic/noober-builder:${CIRCLE_BUILD_NUM}
