version: 2

jobs:
  build:
    docker:
      - image: ${GOOGLE_DOCKER_REPOSITORY}/uber-builder:139
        auth: { username: _json_key, password: "${GOOGLE_CREDENTIALS}" }

    working_directory: ~/uber-builder

    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      - run:
          name: Build image
          command: docker build -t uber-builder .

      - run:
          name: Run tests
          # See https://circleci.com/docs/2.0/building-docker-images/#mounting-folders
          command: |
            docker create \
              -e GOOGLE_CREDENTIALS \
              --name test uber-builder /home/quartic/test/run_tests.sh
            # This permission change (along with the -a below) seems to be necessary to ensure
            # the quartic user inside the container can write to the test directory.
            chmod -R a+rw $(pwd)/test
            docker cp -a $(pwd)/test test:/home/quartic/test
            docker start -a test

      - run:
          name: GCloud auth
          command: google-cloud-auth --with-docker

      - run:
          name: Publish Docker image
          command: docker-tag-and-push uber-builder ${CIRCLE_BUILD_NUM}
