#!/bin/sh
######################################################
# This is really only needed for docker build
######################################################
set -eu
apt-get install --no-install-recommends -y "$@" && rm -rf /var/lib/apt/lists/*