#!/bin/sh
set -eu

echo ${GOOGLE_CREDENTIALS} > ${HOME}/gcloud-service-key.json
gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
rm ${HOME}/gcloud-service-key.json

# TODO: parse args for --with-docker
if [ "$#" -eq 1 ]; then
    docker login -u _json_key -p "${GOOGLE_CREDENTIALS}" https://eu.gcr.io
fi